apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swotitup-secops
  name: swotitup-secops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swotitup-secops
  strategy: {}
  template:
    metadata:
      labels:
        app: swotitup-secops
    spec:
      containers:
        - image: replace
          name: swotitup-secops-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: swotitup-secops
  name: swotitup-secops-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: swotitup-secops
  type: NodePort